.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tha_qt test_tha_qt
clean: FORCE
	$(MAKE) -C .. tha_qt_clean test_tha_qt_clean
check: FORCE
	$(MAKE) -C .. test_tha_qt_check
tha-qt tha-qt.exe: FORCE
	 $(MAKE) -C .. tha_qt
apk: FORCE
	$(MAKE) -C .. tha_qt_apk
